---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: role-k8status
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8status-pod-reader
subjects:
- kind: ServiceAccount
  name: role-k8status
  namespace: ${DEPLOY_NAMESPACE}
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8status
  template:
    metadata:
      labels:
        app: k8status
    spec:
      serviceAccountName: role-k8status
      containers:
      - name: k8status
        image: ${REGISTRY}/${IMAGE_NAME}:${VERSION}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: k8status
spec:
  selector:
    app: k8status
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080